### ISSUE TITLE
Tweet portal is non responsive

### ISSUE THREAD

**Issue by Vanessadiaz1** [trevorbye/TwitterAppReact#12]
The requested tweets is hanging and you are unable to compose and schedule a tweet.

![image](https://user-images.githubusercontent.com/16581573/109589880-e38ddf00-7abf-11eb-8682-ba2f366ceb06.png)
![image](https://user-images.githubusercontent.com/16581573/109589934-f7394580-7abf-11eb-96df-248066defc29.png)

**Comment by diberry** [comment]
This has been fixed. Thank you for reporting.
