### ISSUE TITLE
Time is not updating to the drop down value

### ISSUE THREAD

**Issue by Yonet** [trevorbye/TwitterAppReact#16]
When composing a tweet, the time value seems to change in the drop down but the actual value doesn't update. 
Thanks!

**Comment by diberry** [comment]
Thank you for reporting. #in-progress

**Comment by diberry** [comment]
@Yonet - fix deployed. Please let us know if you continue to experience time/date issues.

**Comment by trevorbye** [comment]
thanks @Yonet, closing

**Comment by Yonet** [comment]
Thank you @diberry @trevorbye, this is an awesome tool.

Currently I am getting "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." when I go to https://mstwitterapp.azurewebsites.net/tweet-portal.

**Comment by diberry** [comment]
@Yonet  the url is just https://mstwitterapp.azurewebsites.net/ which works for me. Does it work for you?

**Comment by Yonet** [comment]
It works now, thanks @diberry

**Comment by diberry** [comment]
@trevorbye Please close.
